project:
  type: website
  output-dir: docs
website:
  title: "SarahRoseCulhane.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Resume.qmd
      - projects.qmd
  page-footer: 
    left: Sarah Culhane, 2025
    right: This website was made with love 
       
format:
  html:
    theme:
     - Yeti
     - styles.scss

editor: visual

