project:
  type: website
  output-dir: docs
website:
  title: "SarahRoseCulhane.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Resume.qmd
      - projects.qmd
       
format:
  html:
    theme: "./styles.scss"
    toc: true

editor: visual

