project:
  type: website
  output-dir: docs
website:
  title: "SarahRoseCulhane.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

